### ISSUE TITLE
omnisharp: line 13: exec: mono: not found

### ISSUE THREAD

**Issue by hgranholm** [OmniSharp/omnisharp-sublime#141] opened 2015-03-30 18:27 UTC
Hi!

This is probably a dumb question, but being such a newbie I can't figure out what exactly is the problem here... OmniSharp worked just fine before the latest update (by Package Control.) I did chmod +x omnisharp already.

The title is the error I get from server output.

**Comment by jchannon** [comment] 2015-03-30 18:41
Sounds like mono isn't in your PATH

**Comment by hgranholm** [comment] 2015-03-30 18:54
Yeah it does sound like it, but it should be... It is in /usr/local/bin/, managed by HomeBrew, and I can type "mono" just fine in a shell:
> echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Am I missing something obvious here? (I also didn't touch any Mono or other settings before or after this OmniSharp upgrade.)

**Comment by jchannon** [comment] 2015-03-30 18:57
Strange it's starting the server via a script in
PrebuiltOmnisharpServer/omnisharp which calls out to mono

**Comment by hgranholm** [comment] 2015-03-30 20:34
Hmm... did something perhaps change in the PrebuiltOmnisharpServer/omnisharp script in this or the previous upgrade? (I think I skipped one version.)

Thanks for the quick reply in any case!

**Comment by jchannon** [comment] 2015-03-30 20:36
1.8.2 was my attempt to chmod +x that file but it may not work due to
package control

I'm a bit lost why it won't work for you :(

**Comment by hgranholm** [comment] 2015-03-30 21:04
Yeah OK if I change the script to exec /usr/local/bin/mono "$DIR/omnisharp.exe" "$@" it connects... but I get tons of errors: looks like nothing is a known identifier. I dunno.

So, *something* to do with the path. But Mono does work just fine in a shell and anyway how could /usr/local/bin/ not be in the path so I have no clue... Oh well, maybe I'll figure it out somehow. Sleep might help :-) Cheers!

**Comment by nosami** [comment] 2015-03-30 21:33
Try starting sublime from the shell using `subl`. That way it will inherit env vars from the shell (including your PATH)

**Comment by hgranholm** [comment] 2015-03-31 07:14
That didn't help either :-/ "mono: not found" again (without the full path in the script)

**Comment by hgranholm** [comment] 2015-03-31 20:43
Okay I'm still not sure what exactly is going on, but I got it running 100% again!

1. Added "export PATH=$PATH:/usr/local/bin" before the "exec mono" line in the bash script.
2. Removed all spaces from all file and folder names up to and including the solution and project.
3. Deleted and remade the project just in case.

So I don't know, but it works now so I'm happy and not touching anything anymore :-)

**Comment by jchannon** [comment] 2015-03-31 21:06
Cool. Maybe point 1 is the key. If you can reproduce we could do a PR for
the script

**Comment by hgranholm** [comment] 2015-03-31 21:25
Yeah. If I comment out that path export line I get mono not found error again in the server output. Put it back and it works. (I still have no clue why, but can reproduce :-)

**Comment by jchannon** [comment] 2015-03-31 21:52
If you run which mono what's the path it returns

**Comment by hgranholm** [comment] 2015-04-01 06:22
Consulted a proper coder at work about this (I'm more of a designer learning to code on the side :-) and it looks like OS X user shells get their default PATH from /etc/paths, so that's why my shell has /usr/local/bin in the PATH even though it's not in my bash profile. But Sublime probably runs bash scripts in a clean environment which doesn't inherit the /etc/paths. This may not be an issue with the official Mono if it perhaps installs into /usr/bin? Homebrew Mono at least installs into /usr/local/bin (or /usr/local/Cellar symlinked to be precise.) (As an ex-Debian user, I much prefer using /usr/local whenever possible :-)

**Comment by hgranholm** [comment] 2015-04-01 06:22
which mono says /usr/local/bin/mono

**Comment by jchannon** [comment] 2015-04-01 09:01
Official mono installs in /usr/bin/mono

I'm guessing people will install mono using homebrew so its probably worth
adding that to the bash script if you want to do a PR

**Comment by hgranholm** [comment] 2015-04-01 16:41
Okay, should be there. (I've only used private Git repos previously, so hopefully I did the pull request right :-)

**Comment by jchannon** [comment] 2015-04-01 17:09
All merged, thanks for the contribution!

**Closed by jchannon** 2015-04-01 17:09 UTC

**Comment by hgranholm** [comment] 2015-04-02 07:14
Thanks for making using Sublime instead of that other horrible thing possible :-)

**Comment by jrock2004** [comment] 2015-04-07 14:20
I just installed the plugin today via package control and I am getting the same error about mono not being found. I installed mono via homebrew so its located in /usr/local/bin. In my .zshrc file I have export PATH="$HOME/bin/tfs:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

Any ideas?

**Comment by jchannon** [comment] 2015-04-07 15:03
The PR done to make sure that path was available for the launcher is not
yet packaged. You can remove the package and then git clone into the
packages directory if you want to be on the bleeding edge or wait a week or
so for a new package release

**Comment by kllmctrl** [comment] 2017-03-05 11:28
Copy mono to path: /usr/local/bin had fix the issue.
